import type { Campaign, Contact, EmailAccount, ScheduledEmail, Sequence, ActivityItem } from "./types";

export const campaigns: Campaign[] = [
  {
    id: "1",
    name: "SaaS Founders Outreach",
    sender: "Alex Rivera",
    senderEmail: "alex@growthco.io",
    status: "active",
    contacts: 482,
    sent: 347,
    opened: 194,
    replied: 61,
    bounced: 8,
    scheduled: 135,
    steps: 3,
    createdAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-09-04T14:22:00Z",
  },
  {
    id: "2",
    name: "Q4 Product Demo Campaign",
    sender: "Alex Rivera",
    senderEmail: "alex@growthco.io",
    status: "active",
    contacts: 318,
    sent: 189,
    opened: 102,
    replied: 38,
    bounced: 5,
    scheduled: 129,
    steps: 4,
    createdAt: "2026-08-28T11:30:00Z",
    updatedAt: "2026-09-04T09:15:00Z",
  },
  {
    id: "3",
    name: "Enterprise Decision Makers",
    sender: "Jordan Lee",
    senderEmail: "jordan@growthco.io",
    status: "paused",
    contacts: 156,
    sent: 156,
    opened: 74,
    replied: 22,
    bounced: 12,
    scheduled: 0,
    steps: 3,
    createdAt: "2026-07-15T08:00:00Z",
    updatedAt: "2026-08-30T16:00:00Z",
  },
  {
    id: "4",
    name: "React Developers Outreach",
    sender: "Alex Rivera",
    senderEmail: "alex@growthco.io",
    status: "draft",
    contacts: 204,
    sent: 0,
    opened: 0,
    replied: 0,
    bounced: 0,
    scheduled: 0,
    steps: 2,
    createdAt: "2026-09-02T13:00:00Z",
    updatedAt: "2026-09-04T11:00:00Z",
  },
  {
    id: "5",
    name: "Mid-Market HR Leaders",
    sender: "Jordan Lee",
    senderEmail: "jordan@growthco.io",
    status: "completed",
    contacts: 290,
    sent: 290,
    opened: 158,
    replied: 49,
    bounced: 14,
    scheduled: 0,
    steps: 4,
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-07-30T17:00:00Z",
  },
  {
    id: "6",
    name: "DevTools Buyer Personas",
    sender: "Sam Park",
    senderEmail: "sam@growthco.io",
    status: "active",
    contacts: 395,
    sent: 221,
    opened: 118,
    replied: 42,
    bounced: 7,
    scheduled: 174,
    steps: 3,
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-09-03T12:00:00Z",
  },
];

export const contacts: Contact[] = [
  { id: "1", firstName: "Sarah", lastName: "Chen", email: "s.chen@acmetech.com", company: "Acme Technologies", title: "VP of Engineering", campaign: "SaaS Founders Outreach", status: "replied", addedAt: "2026-08-14T09:00:00Z" },
  { id: "2", firstName: "Michael", lastName: "Brown", email: "m.brown@novalabs.io", company: "Nova Labs", title: "Co-Founder & CEO", campaign: "SaaS Founders Outreach", status: "active", addedAt: "2026-08-14T09:00:00Z" },
  { id: "3", firstName: "Priya", lastName: "Sharma", email: "priya@cloudworks.ai", company: "CloudWorks", title: "Head of Growth", campaign: "Q4 Product Demo Campaign", status: "active", addedAt: "2026-08-28T11:00:00Z" },
  { id: "4", firstName: "James", lastName: "O'Sullivan", email: "james@vertexio.com", company: "VertexIO", title: "CTO", campaign: "Enterprise Decision Makers", status: "bounced", addedAt: "2026-07-15T08:00:00Z" },
  { id: "5", firstName: "Elena", lastName: "Vasquez", email: "e.vasquez@synthwave.co", company: "Synthwave", title: "Director of Sales", campaign: "Q4 Product Demo Campaign", status: "active", addedAt: "2026-08-28T11:00:00Z" },
  { id: "6", firstName: "David", lastName: "Kim", email: "dkim@stackbridge.io", company: "Stackbridge", title: "Founder", campaign: "React Developers Outreach", status: "active", addedAt: "2026-09-02T13:00:00Z" },
  { id: "7", firstName: "Aisha", lastName: "Okonkwo", email: "aokonkwo@meridian.tech", company: "Meridian Tech", title: "Chief Product Officer", campaign: "Enterprise Decision Makers", status: "replied", addedAt: "2026-07-15T08:00:00Z" },
  { id: "8", firstName: "Ryan", lastName: "Nakamura", email: "ryan@basecamp-ai.com", company: "Basecamp AI", title: "Head of Engineering", campaign: "React Developers Outreach", status: "active", addedAt: "2026-09-02T13:00:00Z" },
  { id: "9", firstName: "Clara", lastName: "Johansson", email: "clara@luminary.io", company: "Luminary IO", title: "Sales Director", campaign: "Mid-Market HR Leaders", status: "active", addedAt: "2026-06-01T08:00:00Z" },
  { id: "10", firstName: "Marcus", lastName: "Wright", email: "m.wright@pivotlabs.com", company: "Pivot Labs", title: "CEO", campaign: "SaaS Founders Outreach", status: "unsubscribed", addedAt: "2026-08-14T09:00:00Z" },
];

export const emailAccounts: EmailAccount[] = [
  { id: "1", email: "alex@growthco.io", name: "Alex Rivera", provider: "google", status: "active", sentToday: 87, dailyLimit: 150, lastActivity: "2026-09-05T09:42:00Z" },
  { id: "2", email: "jordan@growthco.io", name: "Jordan Lee", provider: "google", status: "active", sentToday: 43, dailyLimit: 150, lastActivity: "2026-09-05T08:15:00Z" },
  { id: "3", email: "sam@growthco.io", name: "Sam Park", provider: "smtp", status: "active", sentToday: 62, dailyLimit: 200, lastActivity: "2026-09-05T10:05:00Z" },
  { id: "4", email: "outreach@growthco.io", name: "GrowthCo Outreach", provider: "smtp", status: "error", sentToday: 0, dailyLimit: 200, lastActivity: "2026-09-03T14:00:00Z" },
];

export const scheduledEmails: ScheduledEmail[] = [
  { id: "1", recipient: "Michael Brown", recipientEmail: "m.brown@novalabs.io", subject: "Quick question about Nova Labs", campaign: "SaaS Founders Outreach", sender: "alex@growthco.io", scheduledAt: "2026-09-05T14:00:00Z", status: "pending", step: 2 },
  { id: "2", recipient: "Priya Sharma", recipientEmail: "priya@cloudworks.ai", subject: "Idea for CloudWorks", campaign: "Q4 Product Demo Campaign", sender: "alex@growthco.io", scheduledAt: "2026-09-05T14:30:00Z", status: "pending", step: 1 },
  { id: "3", recipient: "Elena Vasquez", recipientEmail: "e.vasquez@synthwave.co", subject: "Worth a quick conversation?", campaign: "Q4 Product Demo Campaign", sender: "alex@growthco.io", scheduledAt: "2026-09-05T15:00:00Z", status: "queued", step: 3 },
  { id: "4", recipient: "David Kim", recipientEmail: "dkim@stackbridge.io", subject: "Quick question about Stackbridge", campaign: "React Developers Outreach", sender: "alex@growthco.io", scheduledAt: "2026-09-06T09:00:00Z", status: "pending", step: 1 },
  { id: "5", recipient: "Ryan Nakamura", recipientEmail: "ryan@basecamp-ai.com", subject: "Following up, Ryan", campaign: "React Developers Outreach", sender: "alex@growthco.io", scheduledAt: "2026-09-06T09:15:00Z", status: "pending", step: 1 },
  { id: "6", recipient: "Clara Johansson", recipientEmail: "clara@luminary.io", subject: "Closing the loop", campaign: "Mid-Market HR Leaders", sender: "jordan@growthco.io", scheduledAt: "2026-09-04T11:00:00Z", status: "sent", step: 3 },
  { id: "7", recipient: "James O'Sullivan", recipientEmail: "james@vertexio.com", subject: "Quick question about VertexIO", campaign: "Enterprise Decision Makers", sender: "jordan@growthco.io", scheduledAt: "2026-09-03T10:00:00Z", status: "failed", step: 1 },
  { id: "8", recipient: "Marcus Wright", recipientEmail: "m.wright@pivotlabs.com", subject: "Following up, Marcus", campaign: "SaaS Founders Outreach", sender: "alex@growthco.io", scheduledAt: "2026-09-05T16:00:00Z", status: "cancelled", step: 2 },
];

export const sequences: Sequence[] = [
  { id: "1", name: "SaaS Cold Outreach (3-step)", campaign: "SaaS Founders Outreach", steps: 3, contacts: 482, active: true, updatedAt: "2026-09-04T14:22:00Z" },
  { id: "2", name: "Product Demo Follow-up (4-step)", campaign: "Q4 Product Demo Campaign", steps: 4, contacts: 318, active: true, updatedAt: "2026-09-04T09:15:00Z" },
  { id: "3", name: "Enterprise Nurture (3-step)", campaign: "Enterprise Decision Makers", steps: 3, contacts: 156, active: false, updatedAt: "2026-08-30T16:00:00Z" },
  { id: "4", name: "Developer Outreach (2-step)", campaign: "React Developers Outreach", steps: 2, contacts: 204, active: false, updatedAt: "2026-09-04T11:00:00Z" },
];

export const activityItems: ActivityItem[] = [
  { id: "1", type: "reply", text: "Sarah Chen replied to your email", timestamp: "2026-09-05T09:34:00Z", meta: "SaaS Founders Outreach" },
  { id: "2", type: "emails_scheduled", text: "24 emails scheduled for Q4 Product Demo Campaign", timestamp: "2026-09-05T08:00:00Z", meta: "Q4 Product Demo Campaign" },
  { id: "3", type: "campaign_started", text: "Campaign \"DevTools Buyer Personas\" went live", timestamp: "2026-09-04T10:00:00Z", meta: "DevTools Buyer Personas" },
  { id: "4", type: "reply", text: "Aisha Okonkwo replied to your email", timestamp: "2026-09-04T08:52:00Z", meta: "Enterprise Decision Makers" },
  { id: "5", type: "account_connected", text: "sam@growthco.io connected via SMTP", timestamp: "2026-09-03T16:00:00Z" },
  { id: "6", type: "campaign_paused", text: "Campaign \"Enterprise Decision Makers\" was paused", timestamp: "2026-08-30T16:00:00Z", meta: "Enterprise Decision Makers" },
  { id: "7", type: "campaign_created", text: "Campaign \"React Developers Outreach\" created as draft", timestamp: "2026-09-02T13:00:00Z", meta: "React Developers Outreach" },
];

export const chartData = {
  emailActivity: [
    { date: "Aug 30", sent: 142, opened: 78, replied: 14, bounced: 3 },
    { date: "Aug 31", sent: 198, opened: 112, replied: 22, bounced: 5 },
    { date: "Sep 1", sent: 167, opened: 89, replied: 18, bounced: 4 },
    { date: "Sep 2", sent: 214, opened: 124, replied: 31, bounced: 6 },
    { date: "Sep 3", sent: 189, opened: 98, replied: 19, bounced: 2 },
    { date: "Sep 4", sent: 231, opened: 138, replied: 28, bounced: 7 },
    { date: "Sep 5", sent: 143, opened: 82, replied: 17, bounced: 3 },
  ],
  analyticsOverTime: [
    { month: "Apr", sent: 1240, opened: 680, replied: 124 },
    { month: "May", sent: 1890, opened: 1020, replied: 198 },
    { month: "Jun", sent: 2340, opened: 1280, replied: 241 },
    { month: "Jul", sent: 2890, opened: 1640, replied: 298 },
    { month: "Aug", sent: 3420, opened: 1980, replied: 387 },
    { month: "Sep", sent: 1284, opened: 721, replied: 129 },
  ],
};
